analogdevicesinc/meta-adi

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-ad9434-fmc-500ebz.dtsi
Support for zc706-adv7511-ad9434-fmc-500ebz
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>
> meta-adi-xilinx: Add support for ad9434_fmc_zc706

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-fmcdaq2.dtsi
Support for zynq-zc706-adv7511-fmcdaq2.
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>
> meta-adi-xilinx: Add support for daq2_zc706

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-kc705_ad9467_fmc.dtsi
Support for kc705_ad9467_fmc.
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>
> meta-adi-xilinx: Add support for ad9467_fmc_kc705

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-vc707_fmcdaq2.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-adrv9009.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zed-adv7511-ad9467-fmc-250ebz.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zed-adv7511-fmcmotcon2.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynqmp-zcu102-rev10-fmcdaq2.dtsi
This PR adds support for:
- zynq-zed-adv7511-ad9467-fmc-250ebz;
- zynq-zed-adv7511-fmcmotcon2;
- vc707_fmcdaq2;
- zynqmp-zcu102-rev10-fmcdaq2;
- zynq-zc706-adv7511-adrv9009.
> New meta-adi-xilinx supported projects

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
This missing ";;" break the petalinux build...
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>
> meta-adi-xilinx: Fix typo in device tree recipe

- meta-adi-core/conf/layer.conf
- meta-adi-xilinx/conf/layer.conf
This PR adds more important configurations to both meta-adi-core and meta-adi-xilinx. It updates the dependencies list of meta-adi-xilinx and it set's `LAYERSERIES_COMPAT` on both layers.
> Dev add compat series

- meta-adi-core/recipes-core/libiio/libiio.inc
- meta-adi-core/recipes-core/libiio/libiio_0.16.bb
- meta-adi-core/recipes-core/libiio/libiio_0.18.bb
Added libiio_0.18 recipe. This involved some re-work in order to avoid
duplication between 0.16 and 0.18 recipes.
> meta-adi-core: libiio: Add version 0.18

- meta-adi-bsp/COPYING.MIT
- meta-adi-bsp/README.md
- meta-adi-bsp/conf/layer.conf
- meta-adi-bsp/recipes-kernel/linux/linux-adi-configs.inc
- meta-adi-bsp/recipes-kernel/linux/linux-adi-dev.bb
- meta-adi-bsp/recipes-kernel/linux/linux-adi.inc
- meta-adi-bsp/recipes-kernel/linux/linux-adi_2018-R2.bb
This PR addresses #12 
This bsp layer is intended to be used with plain yocto and not with petalinux as meta-adi-xilinx. As for now, there's only a recipe for compiling ADI kernel and the available device tree's. ADI kernel is only compiled for supported machines (as for now, zynq, zynqmp and microblaze) which are defined via COMPATIBLE_MACHINE.This can be easily extended by
appending the recipe or directly changing it. Also note, that for building for example for zc706-zynq7 machine, the meta-xilinx-bsp layer has to be added since this layer is not redefining machines which are already defined in another yocto layer's.
> Dev add meta bsp layer

- meta-adi-xilinx/README.md
- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
In the previous mechanism, the selected ADI devicetree was just being copied and overwriting system-user.dtsi which is the file intended to be used by the user when extending the core devicetree. So, with that mechanism, it was impossible or very cumbersome to extend the ADI devicetree being used. So that, now we just copy the selected dts to a file named analog-devices.dtsi which is then included in the begining of the system-user.dtsi file. This way, the user can freely customize the system-user.dtsi file to his needs.
This should close #28
> Dev dtsi extension

- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_%.bbappend
Since the kernel recipe was just overwriting `SRC_URI`, any config
fragment created with `petalinux-config -c kernel` was not being copied
to the build WORKDIR. Hence, it was not possible to add/remove kernel
configurations on top of the selected kernel defconfig file.
> meta-adi-xilinx: kernel: Allow config fragments

- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynqmp-zcu102-rev10-adrv9009.dtsi
The hdl project and the meta layer were out of sync. misc_clk_2 is no
longer used so that we don't have to remove it. This would actually lead
to a build fail of the devicetree.
> meta-adi-xilinx: Fix zcu102-rev10-adrv9009 project

- meta-adi-bsp/recipes-kernel/linux/linux-adi-dev.bb
- meta-adi-bsp/recipes-kernel/linux/linux-adi.inc
- meta-adi-core/recipes-core/libad9361-iio/libad9361-iio_0.2.bb
- meta-adi-core/recipes-core/libiio/libiio.inc
- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_%.bbappend
Otherwise it pulls master and it fails.
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
> treewide: use 2018_R2 branch for all projects

- meta-adi-core/recipes-core/libiio/libiio_0.16.bb
- meta-adi-core/recipes-core/libiio/libiio_0.18.bb
- meta-adi-xilinx/README.md
- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-kernel/linux/linux-adi.inc
- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_adi-2018_R2.bb
This PR adds support for petalinux 2018_R2 and hdl_2018_R2. The kernel recipe got some refactoring that will be also added to the other branches.
> Add support for 2018_R2

- meta-adi-xilinx/README.md
The petalinux user guide links were pointing to 2018_R3. Set them to
2018_R2.
> meta-adi-xilinx: docs: Fix README links

- meta-adi-core/recipes-core/fru-tools/fru-tools_0.8.1.5.bb
- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
- meta-adi-core/recipes-core/libad9361-iio/libad9361-iio_0.2.bb
- meta-adi-xilinx/README.md
- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_adi-2019_R1.bb
This PR adds support for buiding petalinux without internet access...
In addition, it fixes the branch being checked out on fru-tools.
> [2019_R1] Offline support

- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
Set 2019_R1 as the branch to checkout. Master was being used by
default...
> meta-adi-core: jesd-status: Fix branch to checkout

- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
Explicitly set master as the branch to checkout.
> meta-adi-core: jesd-status: Set branch to checkout

- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
The fetch function fails because BRANCH was being defined with a
different name.
Fixes: fa89041 ("meta-adi-core: jesd-status: Fix branch to checkout")
> meta-adi-xilinx: jesd_status: Fix wrong name

- Dockerfile.petalinux
- Dockerfile.yocto
This adds Docker images to easily build yocto and petalinux without
having to install all the dependencies. Also, for petalinux, the docker
image can be used to install the SDK on the system.
> meta-adi: Add Docker images

- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
- meta-adi-core/recipes-core/libiio/libiio.inc
This patch makes libiio and jesd to use https to fetch the git repos.
> meta-adi-core: Use https to fetch git repo

- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-kcu105_adrv9371x.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-adrv9009.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-adrv9371.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zc706-adv7511-fmcomms11.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynqmp-zcu102-rev10-adrv9009.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynqmp-zcu102-rev10-adrv9371.dtsi
Some projects fail to build due to some renaming in the hdl projects.
> meta-adi-xilinx: devicetree: Fix projects build

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
The example to be used when dts overlays are enabled is based on zcu102.
Hence, if we want it to be uploaded to WORKDIR, it must be added to the
zynqmp SRC_URI override.
Fixes: 6a404e34 ("meta-adi-xilinx: device-tree: Minimize files to put in WORKDIR")
> meta-adi-xilinx: Fix SRC_URI devicetree overlay example

- meta-adi-xilinx/README.md
Fix link to petalinux-user-image recipe.
> meta-adi-xilinx: doc: Fix README link

- meta-adi-xilinx/conf/layer.conf
- meta-adi-xilinx/dynamic-layers/meta-plnx-generated/recipes-core/images/petalinux-user-image.bbappend
- meta-adi-xilinx/recipes-support/adrv9009-zu11eg-fan-control-daemon/adrv9009-zu11eg-fan-control_dev.bb
Same as #88 but with the new recipe applied to 2019_R2 so that it checks out the 2019_R2 branch
> adrv9009 zu11eg fan control 2019_R2

- meta-adi-xilinx/README.md
Fix bad links to `fpga-manager-util_%.bbappend` and `fs-boot_%.bbappend`
Fixes: 185dd26 ("meta-adi-xilinx: update readme file")
> meta-adi-xilinx: fix readme

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zed-adrv9002-rx2tx2.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zed-adv7511-adrv9002-rx2tx2.dtsi
- meta-adi-xilinx/recipes-bsp/device-tree/files/pl-delete-nodes-zynq-zed-adv7511-adrv9002.dtsi
Renamed ADRV9002 Zed pl-delete-nodes dtsi files to match changes made to ADI Linux Kernel 2019_R2 branch.
> Import the Zed ADRV9002 dtsi renames onto 2019_R2 to match with ADI Linux branch 2019_R2 

- meta-adi-xilinx/recipes-support/libiio/libiio_%.bbappend
This fix is still related with the changes introduced by [1]. If
'HAVE_DNS_SD' is ON, we need to have the correspondent avahi dependencies
set... However, for microblaze builds, zeroconf is not part of the
petalinux 'DISTRO_FEATURES'. Hence, we disable 'DHAVE_DNS_SD' if zeroconf
is not present.
[1]: https://github.com/analogdevicesinc/libiio/pull/680
> meta-adi-xilinx: libiio: fix build for microblaze

- meta-adi-xilinx/recipes-support/libiio/libiio_%.bbappend
Add the sysvinit patch in the same SRC_URI append line. Otherwise, the
'+=' operator has precedence over '_append' which means that the ';branch='
key will not be applied to the 'git://' URI and hence, we cannot specify
the branch to checkout. It will always use master no matter what is
given in BRANCH'.
Fixes: cd042513d600 ("meta-adi-xilinx: libiio: remove lsb runtime dependency")
> meta-adi-xilinx: libiio: fix branch selection

- meta-adi-core/recipes-core/fru-tools/fru-tools_0.8.1.5.bb
- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
- meta-adi-core/recipes-core/libad9361-iio/libad9361-iio_0.2.bb
- meta-adi-xilinx/README.md
- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_%.bbappend
- meta-adi-xilinx/recipes-support/adrv9009-zu11eg-fan-control-daemon/adrv9009-zu11eg-fan-control_dev.bb
- meta-adi-xilinx/recipes-support/libiio/libiio_%.bbappend
Support petalinux 2021.2 version. The support was pretty straight and boils down to readme and git sha updates (also libiio was updated so that the package name reflects the right version)
> petalinux 2021.2 support

- meta-adi-core/conf/layer.conf
* Tested by building libiio for use with gnuradio.
Signed-off-by: Philip Balister <philip@balister.org>
> layer.conf: Add support for Dunfell branch

- meta-adi-xilinx/recipes-bsp/device-tree/device-tree.bbappend
If someone uses the recommendations from the README.md file to create a custom device tree, the build runs into an error, because cp tries to use the same values for source and destination if "KERNEL_DTB_PATH" is set to "workdir". This results in a return value unequal to zero and stops executing the build process.
Moreover, the string comparison from USE_KERNEL_SOURCES did not contain double quotes, thus it was not interpreted as a string.
Signed-off-by: Andre Werner <andre.werner@systec-electronic.com>
> device-tree: Fix issue for custom DTS

- meta-adi-xilinx/recipes-support/libiio/libiio_%.bbappend
Libiio renamed the master branch to main. More importantly, it moved to libiio v1.0 which is not backward compatible (at least for now) with libiio v0. Hence, all the projects that 'DEPEND' on libiio will fail to compile in meta-adi. Since it might take some time for those projects to be converted, let's move to the v0 branch and update the package 'PV' accordingly.
Fixes #128
> meta-adi-xilinx: recipes-support: libiio: move to libbio-v0 branch

- meta-adi-xilinx/dynamic-layers/meta-petalinux/recipes-core/images/petalinux-image-minimal.bbappend
On Microblaze, zeroconf is not enabled so that we can remove avahi-daemon from the image. However, we were trying to do the remove action after the microblaze override and so, the package was still included in the image. Fix it by placing the override in it's place after the ':remove' action.
> meta-adi-xilinx: petalinux-image-minimal: really remove avahi-daemon

- meta-adi-xilinx/recipes-kernel/linux/linux-xlnx_%.bbappend
We now use main in linux and master was removed. So update it in here.
> meta-adi-xilinx: linux: rename 'master' > 'main'

- .gitignore
This is necessary for maintaining the two syvinitscript.patch files located in: 
1. meta-adi-xilinx/recipes-support/adrv9009-zu11eg-fan-control-daemon/files/ 
2. meta-adi-xilinx/recipes-support/libiio/files/
> gitignore: don't ignore patch files

- ci/petalinux-build.sh
Some artifacts are still not available in the 'main' export so that we try to use the legacy 'master'. However, get_hdl_artifacts was doing an 'exit 1' in case no artifact was found. Hence, we don't have a shot in trying the 'master' path.
> ci: petalinux-build: fix getting hdl artifacts

- meta-adi-xilinx/README.md
If the previous syntax is used, We encounter this error: **Exception: bb.fetch2.MalformedUrl: The URL: 'pl-delete-nodes-custom-devicetree.dtsi' is invalid and cannot be interpreted**.
> meta-adi-xilinx: readme: fix bitbake syntax

- meta-adi-xilinx/recipes-support/libiio/libiio_%.bbappend
The offline git hash for libiio was wrong and did not existed. Fix it...
Should fix #162
> meta-adi-xilinx: libiio: fix offline build

- meta-adi-xilinx/dynamic-layers/meta-petalinux/recipes-core/images/petalinux-image-minimal.bbappend
- meta-adi-xilinx/recipes-support/pyadi-iio/pyadi-iio_0.0.19.bb
Adds a recipe for pyADI-IIO to include the Python package in meta-adi based projects.
This was requested by a customer who wished to run pyADI-IIO based Python projects directly on their FPGA hardware. It seemed like a useful addition to include this as part of the meta-adi layer.
> Add pyADI-IIO Recipe
